In [1]:
import pandas as pd

In [2]:
pd.__file__

'/workspaces/docker-postgres/pipeline/.venv/lib/python3.13/site-packages/pandas/__init__.py'

In [3]:
import requests, io
prefix = "https://d37ci6vzurychx.cloudfront.net/trip-data"
url = f"{prefix}/yellow_tripdata_2021-01.parquet"

import pyarrow.parquet as pq

# table = pq.read_table(url)
# df2 = table.to_pandas()

# prefix="https://d37ci6vzurychx.cloudfront.net/trip-data/"
# url=f'{prefix}/yellow_tripdata_2021-01.parquet'
# resp = requests.get(url)
# resp.raise_for_status()   # ensure no 403/404

# df = pd.read_parquet(io.BytesIO(resp.content))
# df.head()

In [4]:
prefix="https://d37ci6vzurychx.cloudfront.net/trip-data"
url=f'{prefix}/yellow_tripdata_2021-01.parquet'
df = pd.read_parquet(url)
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5,NaN
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,NaN
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0,NaN
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0,NaN
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5,NaN

"Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',\n       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',\n       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',\n       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',\n       'total_amount', 'congestion_surcharge', 'airport_fee'],\n      dtype='str')"

In [5]:
len(df)

1369769

In [6]:
df.VendorID

0          1
1          1
2          1
3          1
4          2
          ..
1369764    2
1369765    2
1369766    2
1369767    6
1369768    2
Name: VendorID, Length: 1369769, dtype: int64

In [7]:
df.tpep_pickup_datetime

0         2021-01-01 00:30:10
1         2021-01-01 00:51:20
2         2021-01-01 00:43:30
3         2021-01-01 00:15:48
4         2021-01-01 00:31:49
                  ...
1369764   2021-01-31 23:03:00
1369765   2021-01-31 23:29:00
1369766   2021-01-31 23:25:00
1369767   2021-01-31 23:01:06
1369768   2021-01-31 23:08:29
Name: tpep_pickup_datetime, Length: 1369769, dtype: datetime64[us]

In [8]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    # nrows=100,
    dtype=dtype,
    parse_dates=parse_dates
)

In [9]:
import requests, io
prefix = "https://d37ci6vzurychx.cloudfront.net/trip-data"
url = f"{prefix}/yellow_tripdata_2021-01.parquet"
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]
df2= pd.read_parquet(url)
df2=df2.astype(dtype)
for col in parse_dates:
    df2[col]=pd.to_datetime(df2[col])

df2.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5,NaN
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,NaN
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0,NaN
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0,NaN
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5,NaN

In [10]:
df2.tpep_pickup_datetime

0         2021-01-01 00:30:10
1         2021-01-01 00:51:20
2         2021-01-01 00:43:30
3         2021-01-01 00:15:48
4         2021-01-01 00:31:49
                  ...
1369764   2021-01-31 23:03:00
1369765   2021-01-31 23:29:00
1369766   2021-01-31 23:25:00
1369767   2021-01-31 23:01:06
1369768   2021-01-31 23:08:29
Name: tpep_pickup_datetime, Length: 1369769, dtype: datetime64[us]

In [11]:
df.tpep_pickup_datetime
max_length=len(df)
max_length

1369769

In [13]:
from sqlalchemy import create_engine
engine=create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [15]:
print(pd.io.sql.get_schema(df2, name='yellow_taxi_data',con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53),
	airport_fee FLOAT(53)
)

In [16]:
df2.head(0).to_sql(
    name='yellow_taxi_data',
    con=engine,
    schema='golden',
    if_exists='replace',   # or 'append'
    # index=False
)

0

In [42]:
df.head(0).to_sql(
    name='yellow_taxi_data',
    con=engine,
    # schema='golden',
    if_exists='replace',   # or 'append'
    # index=False
)

PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)

In [44]:
from sqlalchemy import create_engine, text

engine = create_engine("postgresql://root:root@localhost:5432/ny_taxi")

with engine.connect() as conn:
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS golden"))
    conn.commit()


# Create empty table structure
df.head(0).to_sql(
    name='yellow_taxi_data',
    con=engine,
    schema='golden',
    if_exists='replace',
    index=False
)

0

In [17]:
df_length=len(df2)
print(df_length)

1369769

In [50]:
df_iter=pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator= True,
    chunksize=100000)

In [18]:
def df_to_iter(df, chunksize=100000):
    for start in range(0, df_length, chunksize):
        yield df.iloc[start:start+chunksize]

df_iter = df_to_iter(df2, chunksize=100000)

df=next(df_iter)
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5,NaN
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,NaN
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0,NaN
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0,NaN
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-04 14:04:31,2021-01-04 14:08:52,3,0.70,1,N,234,224,2,5.0,2.5,0.5,0.00,0.0,0.3,8.30,2.5,NaN
99996,1,2021-01-04 14:18:46,2021-01-04 14:35:45,2,3.30,1,N,234,236,1,14.5,2.5,0.5,3.55,0.0,0.3,21.35,2.5,NaN
99997,1,2021-01-04 14:42:41,2021-01-04 14:59:22,2,4.70,1,N,236,79,1,17.0,2.5,0.5,4.05,0.0,0.3,24.35,2.5,NaN
99998,2,2021-01-04 14:39:02,2021-01-04 15:09:37,2,17.95,2,N,132,148,1,52.0,0.0,0.5,5.00,0.0,0.3,60.30,2.5,NaN
99999,2,2021-01-04 14:49:36,2021-01-04 14:54:44,5,0.37,1,N,236,236,2,5.0,0.0,0.5,0.00,0.0,0.3,8.30,2.5,NaN

In [19]:
!uv add tqdm

Resolved 119 packages in 1ms
Checked 15 packages in 0.45ms

In [20]:
from tqdm.auto import tqdm

In [21]:
for chunk in tqdm(df_iter):
    chunk.to_sql(
        name='yellow_taxi_data',
        schema='golden',
        con=engine,
        if_exists='append',
        index=False
    )

0it [00:00, ?it/s]

In [40]:
for chunk in df_iter:
    print(len(chunk))

In [30]:
from sqlalchemy import create_engine, text
with engine.connect() as conn:
    conn.execute(text("select * from golden.yellow_taxi_data"))
    conn.commit()

In [38]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM golden.yellow_taxi_data LIMIT 5"))
    rows = result.fetchall()

for row in rows:
    print(row)